FROM ubuntu:18.04

RUN apt update && apt upgrade -y
RUN apt install curl zip unzip make ninja-build python3 python3-distutils git build-essential libssl-dev -y

WORKDIR /src/cmake
RUN curl --fail-early --location https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0.tar.gz \
  | tar --gz --extract --strip-components=1 --file -

RUN ./bootstrap --parallel=`nproc`
RUN make --jobs $(nproc)
RUN make install
