name: Publish
'on':
  push:
    tags:
    - v*
permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write
jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - id: create_release
      name: Create release
      run: echo "upload_url=hello" >> "$GITHUB_OUTPUT"
