version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: theorian/cpp-toolchain-base
  host_base:
    build:
      context: .
      dockerfile: Dockerfile.host_base
    image: theorian/cpp-toolchain-host-base
  linux_kernel:
    build:
      context: .
      dockerfile: Dockerfile.kernel
      args:
        SYSROOT_OUTPUT_DIR: "${SYSROOT_OUTPUT_DIR}"
        LINUX_KERNEL_VERSION: ${LINUX_KERNEL_VERSION}
    image: theorian/linux-kernel:${LINUX_KERNEL_VERSION}
    depends_on:
      - host_base
  glibc:
    build:
      context: .
      dockerfile: Dockerfile.glibc
      args:
        SYSROOT_OUTPUT_DIR: "${SYSROOT_OUTPUT_DIR}"
        LINUX_KERNEL_VERSION: ${LINUX_KERNEL_VERSION}
        GLIBC_VERSION: ${GLIBC_VERSION}
    image: theorian/glibc:${GLIBC_VERSION}
    depends_on:
      - host_base
      - linux_kernel
  gcc7:
    build:
      context: .
      dockerfile: Dockerfile.gcc_root
      args:
        SYSROOT_OUTPUT_DIR: "${SYSROOT_OUTPUT_DIR}"
        GLIBC_VERSION: ${GLIBC_VERSION}
        BINUTILS_VERSION: "2.33.1"
        TARGET_GCC_VERSION: "7.5.0"
    image: theorian/gcc:7.5.0
    depends_on:
      - host_base
      - glibc
  gcc8:
    build:
      context: .
      dockerfile: Dockerfile.gcc
      args:
        SYSROOT_OUTPUT_DIR: "${SYSROOT_OUTPUT_DIR}"
        GLIBC_VERSION: ${GLIBC_VERSION}
        HOST_GCC_VERSION: "7.5.0"
        BINUTILS_VERSION: "2.36"
        TARGET_GCC_VERSION: "8.5.0"
    image: theorian/gcc:8.5.0
    depends_on:
      - base
      - glibc
      - gcc7
  gcc9:
    build:
      context: .
      dockerfile: Dockerfile.gcc
      args:
        SYSROOT_OUTPUT_DIR: "${SYSROOT_OUTPUT_DIR}"
        GLIBC_VERSION: ${GLIBC_VERSION}
        HOST_GCC_VERSION: "8.5.0"
        BINUTILS_VERSION: "2.38"
        TARGET_GCC_VERSION: "9.5.0"
    image: theorian/gcc:9.5.0
    depends_on:
      - base
      - glibc
      - gcc8
  gcc10:
    build:
      context: .
      dockerfile: Dockerfile.gcc
      args:
        SYSROOT_OUTPUT_DIR: "${SYSROOT_OUTPUT_DIR}"
        GLIBC_VERSION: ${GLIBC_VERSION}
        HOST_GCC_VERSION: "9.5.0"
        BINUTILS_VERSION: "2.40"
        TARGET_GCC_VERSION: "10.5.0"
    image: theorian/gcc:10.5.0
    depends_on:
      - base
      - glibc
      - gcc9
  gcc11:
    build:
      context: .
      dockerfile: Dockerfile.gcc
      args:
        SYSROOT_OUTPUT_DIR: "${SYSROOT_OUTPUT_DIR}"
        GLIBC_VERSION: ${GLIBC_VERSION}
        HOST_GCC_VERSION: "10.5.0"
        BINUTILS_VERSION: "2.42"
        TARGET_GCC_VERSION: "11.5.0"
    image: theorian/gcc:11.5.0
    depends_on:
      - base
      - glibc
      - gcc10
  gcc12:
    build:
      context: .
      dockerfile: Dockerfile.gcc
      args:
        SYSROOT_OUTPUT_DIR: "${SYSROOT_OUTPUT_DIR}"
        GLIBC_VERSION: ${GLIBC_VERSION}
        HOST_GCC_VERSION: "11.5.0"
        BINUTILS_VERSION: "2.42"
        TARGET_GCC_VERSION: "12.4.0"
    image: theorian/gcc:12.4.0
    depends_on:
      - base
      - glibc
      - gcc11
  gcc13:
    build:
      context: .
      dockerfile: Dockerfile.gcc
      args:
        SYSROOT_OUTPUT_DIR: "${SYSROOT_OUTPUT_DIR}"
        GLIBC_VERSION: ${GLIBC_VERSION}
        HOST_GCC_VERSION: "12.4.0"
        BINUTILS_VERSION: "2.42"
        TARGET_GCC_VERSION: "13.3.0"
    image: theorian/gcc:13.3.0
    depends_on:
      - base
      - glibc
      - gcc12
  gcc14:
    build:
      context: .
      dockerfile: Dockerfile.gcc
      args:
        SYSROOT_OUTPUT_DIR: "${SYSROOT_OUTPUT_DIR}"
        GLIBC_VERSION: ${GLIBC_VERSION}
        HOST_GCC_VERSION: "13.3.0"
        BINUTILS_VERSION: "2.42"
        TARGET_GCC_VERSION: "14.2.0"
    image: theorian/gcc:14.2.0
    depends_on:
      - base
      - glibc
      - gcc13
