name: Build and publish GCC

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version that will be appended to release name and tag. Can be anything (i.e. does not have to be a number).'
        required: true
      sysroot_release:
        description: 'Version of sysroot release to use as a toolchain sysroot.'
        required: true
      force_rebuild:
        description: 'If set rebuilds and reuploads existing builds for given release version (yes/no).'
        default: 'no'
        required: false

permissions:
  contents: write

env:
  BASE_IMAGE_CACHE_KEY: gcc-toolchain-base-image-
  BASE_IMAGE_CACHE_PATH: ci/cache/docker/gcc
  RELEASE_TAG: gcc-${{ github.event.inputs.release_version }}

jobs:
  base_image:
    name: Build base image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Setup PYTHONPATH
        run: echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV
      - name: Verify if GCC toolchain base image cached
        id: cache-gcc-toolchain-base-image
        uses: actions/cache@v4
        with:
          path: ${{ env.BASE_IMAGE_CACHE_PATH }}
          key: ${{ env.BASE_IMAGE_CACHE_KEY }}${{ hashFiles('gcc/Dockerfile.base') }}
          lookup-only: true
      - name: Build GCC toolchain base image
        run: |
          python3 image/base_image.py                     \
            --toolchain=gcc                               \
            --cache-path=${{ env.BASE_IMAGE_CACHE_PATH }} \
            --op=store
        if: steps.cache-gcc-toolchain-base-image.outputs.cache-hit != 'true'

  gcc:
    name: Build GCC ${{ matrix.version.gcc }}
    runs-on: ubuntu-latest-16cpu
    needs: base_image

    strategy:
      max-parallel: 1
      matrix:
        version:
          - gcc: "7.5.0"
            binutils: "2.33.1"
          - host: "7.5.0"
            gcc: "8.5.0"
            binutils: "2.36"
          - host: "8.5.0"
            gcc: "9.5.0"
            binutils: "2.38"
          - host: "9.5.0"
            gcc: "10.5.0"
            binutils: "2.40"
          - host: "10.5.0"
            gcc: "11.5.0"
            binutils: "2.42"
          - host: "11.5.0"
            gcc: "12.4.0"
            binutils: "2.42"
          - host: "12.4.0"
            gcc: "13.3.0"
            binutils: "2.42"
          - host: "13.3.0"
            gcc: "14.2.0"
            binutils: "2.42"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Setup PYTHONPATH
        run: echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV
      - name: Download GCC toolchain base images from cache
        uses: actions/cache@v4
        with:
          path: ${{ env.BASE_IMAGE_CACHE_PATH }}
          key: ${{ env.BASE_IMAGE_CACHE_KEY }}${{ hashFiles('gcc/Dockerfile.base') }}
          fail-on-cache-miss: true
      - name: Load GCC toolchain base image
        run: |
          python3 image/base_image.py                     \
            --toolchain=gcc                               \
            --cache-path=${{ env.BASE_IMAGE_CACHE_PATH }} \
            --op=load
      - name: Download sysroot
        id: download-sysroot
        uses: robinraju/release-downloader@v1
        with:
          tag: sysroot-${{ github.event.inputs.sysroot_release }}
          fileName: sysroot-*.tar.xz
      - name: Create GCC release
        uses: softprops/action-gh-release@v2
        with:
          name: GCC ${{ github.event.inputs.release_version }} (SYSROOT ${{ github.event.inputs.sysroot_release }})
          tag_name: ${{ env.RELEASE_TAG }}
      - name: Build and publish GCC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 gcc/build_gcc.py                                                             \
            --repository=${{ github.repository }}                                              \
            --release-id=${{ env.RELEASE_TAG }}                                                \
            --sysroot-path=${{ fromJson(steps.download-sysroot.outputs.downloaded_files)[0] }} \
            --force-rebuild=${{ github.event.inputs.force_rebuild }}                           \
            --host-gcc-version=${{ matrix.version.host }}                                      \
            --gcc-version=${{ matrix.version.gcc }}                                            \
            --binutils-version=${{ matrix.version.binutils }}
